<?php

namespace GSB\gsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatRepository extends EntityRepository {
    //put your code here
}
