<?php

namespace GSB\gsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends EntityRepository {

//    public function findByLoginAndMdp($login, $mdp) {
//        $queryBuilder = $this->createQueryBuilder('unVisiteur');
//        $queryBuilder->where('unVisiteur.login = :login')
//                ->setParameter('login', $login)
//                ->andWhere('unVisiteur.mdp = :mdp')
//                ->setParameter('mdp', $mdp);
//        $result = $queryBuilder->getQuery()->getOneOrNullResult();
//
//        return $result;
//    }

}
