# Resources/config/parameters
parameters:
  pdo.class: PDO
  pdo.attr_errmode: 3
  pdo.erromode_exception: 2
  pdo.options: 
    %pdo.attr_errmode%: %pdo.erromode_exception%
  database.db1.dsn: mysql:host=localhost;dbname=gsbFrais
  database.db1.username: root
  database.db1.password: azerty